#!/bin/bash

go build cleanDirectory.go
./cleanDirectory

rm -rf structCustom/structCustom_*
echo "tmp" > structCustom/structCustom_1

rm  -rf structDirectory/queries
mkdir structDirectory/queries

rm structDirectory/curCustomNumber
echo "0" > structDirectory/curCustomNumber

echo "Cleaned."
