#!/bin/bash

#"dbInfo" file stores creds
source dbInfo

#if "gs" (generate structs) is called or structs folder doesn't exist
if [ "$1" == "gs" ] || [ "$2" == "gs" ] || [ ! -d "structs" ] ; then
	go build main.go
	./main $USERNAME $PASSWORD $ENVIRONMENT 1
elif [ "$1" == "cs" ] || [ "$2" == "cs" ] ; then
	go build structCustomGenerator.go
	./structCustomGenerator $USERNAME $PASSWORD $ENVIRONMENT
	go build main.go
	./main $USERNAME $PASSWORD $ENVIRONMENT 0
else
	go build main.go	
	./main $USERNAME $PASSWORD $ENVIRONMENT 0
fi
