package genStructs
var ValidStruct = map[string]bool {
	"asn" : true,
	"cachegroup" : true,
	"cachegroup_parameter" : true,
	"deliveryservice" : true,
	"deliveryservice_regex" : true,
	"deliveryservice_server" : true,
	"deliveryservice_tmuser" : true,
	"division" : true,
	"goose_db_version" : true,
	"hwinfo" : true,
	"job" : true,
	"job_agent" : true,
	"job_result" : true,
	"job_status" : true,
	"log" : true,
	"parameter" : true,
	"phys_location" : true,
	"profile" : true,
	"profile_parameter" : true,
	"regex" : true,
	"region" : true,
	"role" : true,
	"server" : true,
	"servercheck" : true,
	"staticdnsentry" : true,
	"status" : true,
	"tm_user" : true,
	"to_extension" : true,
	"type" : true,
	"condensedasn" : true,
	"crystal" : true,
	"deliveryservicesdenver" : true,
	"himark" : true,
}
